// <auto-generated />
using System;
using GobEfi.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GobEfi.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181211182539_NuevaEntidadReporte_Relacionada_ReportesRol")]
    partial class NuevaEntidadReporte_Relacionada_ReportesRol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GE.Data.Entities.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName");

                    b.Property<string>("ControllerName");

                    b.Property<string>("Icono");

                    b.Property<string>("IdTag");

                    b.Property<long>("MenuPanelId");

                    b.Property<string>("Nombre");

                    b.Property<int>("Orden");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("MenuPanelId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("GE.Data.Entities.MenuPanel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<string>("TagHref");

                    b.Property<string>("TagId");

                    b.HasKey("Id");

                    b.ToTable("MenuPanel");
                });

            modelBuilder.Entity("GE.Data.Entities.Permisos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Escritura");

                    b.Property<bool>("Lectura");

                    b.Property<long>("MenuId");

                    b.Property<string>("RolId");

                    b.Property<long?>("SubMenuId");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.HasIndex("SubMenuId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("GE.Data.Entities.Reporte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("GE.Data.Entities.ReporteRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ReporteId");

                    b.Property<string>("RolId");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.HasIndex("RolId");

                    b.ToTable("ReportesRol");
                });

            modelBuilder.Entity("GE.Data.Entities.SubMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action");

                    b.Property<string>("Controller");

                    b.Property<string>("Icono");

                    b.Property<long>("MenuId");

                    b.Property<string>("Nombre");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("SubMenu");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.ArchivoAdjunto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Descripcion");

                    b.Property<long>("DivisionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<long>("TipoArchivoId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Url");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TipoArchivoId");

                    b.ToTable("ArchivoAdjuntos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Componente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long>("DivisionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<double>("Superficie");

                    b.Property<bool>("TieneAislacion");

                    b.Property<long>("TipoAislacionId");

                    b.Property<long>("TipoMaterialId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TipoAislacionId");

                    b.HasIndex("TipoMaterialId");

                    b.ToTable("Componente");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Componente");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Compra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<double>("Consumo");

                    b.Property<double>("Costo");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("DivisionId");

                    b.Property<long>("EnergeticoId");

                    b.Property<string>("EstadoValidacion")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("sin_revision");

                    b.Property<long>("FacturaId");

                    b.Property<DateTime>("FechaCompra");

                    b.Property<DateTime>("FinLectura");

                    b.Property<DateTime>("InicioLectura");

                    b.Property<string>("ModifiedBy");

                    b.Property<long?>("NumeroClienteId");

                    b.Property<string>("Observacion");

                    b.Property<long?>("UnidadMedidaId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EnergeticoId");

                    b.HasIndex("FacturaId")
                        .IsUnique();

                    b.HasIndex("NumeroClienteId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.CompraMedidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CompraId");

                    b.Property<double>("Consumo");

                    b.Property<long>("MedidorId");

                    b.Property<long?>("ParametroMedicionId");

                    b.Property<long?>("UnidadMedidaId");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("MedidorId");

                    b.HasIndex("ParametroMedicionId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("CompraMedidor");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Comuna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<long?>("ProvinciaId");

                    b.Property<long?>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("RegionId");

                    b.ToTable("Comunas");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Division", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("AnyoConstruccion");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("EdificioId");

                    b.Property<int>("Funcionarios");

                    b.Property<double?>("Latitud");

                    b.Property<double?>("Longitud");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<int?>("OldId");

                    b.Property<string>("Pisos");

                    b.Property<bool>("ReportaPMG");

                    b.Property<long>("ServicioId");

                    b.Property<double?>("Superficie");

                    b.Property<long>("TipoAgrupamientoId");

                    b.Property<long>("TipoPropiedadId");

                    b.Property<long>("TipoUnidadId");

                    b.Property<long?>("TipoUsoId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("EdificioId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TipoAgrupamientoId");

                    b.HasIndex("TipoPropiedadId");

                    b.HasIndex("TipoUnidadId");

                    b.HasIndex("TipoUsoId");

                    b.ToTable("Divisiones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Edificio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<double?>("Altitud");

                    b.Property<string>("Calle");

                    b.Property<long?>("ComunaId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Direccion");

                    b.Property<double?>("Latitud");

                    b.Property<double?>("Longitud");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Numero");

                    b.Property<int?>("OldId");

                    b.Property<long>("TipoEdificioId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ComunaId");

                    b.HasIndex("TipoEdificioId");

                    b.ToTable("Edificios");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EmpresaDistribuidora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("EnergeticoId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<long>("OldId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("EnergeticoId");

                    b.ToTable("EmpresaDistribuidoras");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EmpresaDistribuidoraComuna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<long?>("ComunaId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long?>("EmpresaDistribuidoraId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ComunaId");

                    b.HasIndex("EmpresaDistribuidoraId");

                    b.ToTable("EmpresasDistribuidoraComunas");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Energetico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Icono");

                    b.Property<string>("ModifiedBy");

                    b.Property<bool>("Multiple");

                    b.Property<string>("Nombre");

                    b.Property<bool>("PermiteMedidor");

                    b.Property<int>("Posicion");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.ToTable("Energeticos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EnergeticoDivision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("DivisionId");

                    b.Property<long>("EnergeticoId");

                    b.Property<string>("ModifiedBy");

                    b.Property<long?>("NumeroClienteId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EnergeticoId");

                    b.HasIndex("NumeroClienteId");

                    b.ToTable("EnergeticoDivision");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EnergeticoUnidadMedida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<double>("Calor");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<double>("Densidad");

                    b.Property<long>("EnergeticoId");

                    b.Property<double>("Factor");

                    b.Property<string>("ModifiedBy");

                    b.Property<long>("UnidadMedidaId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("EnergeticoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("EnergeticoUnidadesMedidas");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Equipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("AnyoCompra");

                    b.Property<int>("Cantidad");

                    b.Property<int>("CostoMantencion");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long?>("DivisionId");

                    b.Property<long?>("EnergeticInId");

                    b.Property<long?>("EnergeticOutId");

                    b.Property<long>("EnergeticoIn");

                    b.Property<long>("EnergeticoOut");

                    b.Property<double>("HorasUso");

                    b.Property<int>("Inversion");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<string>("ModifiedBy");

                    b.Property<long>("ModoOperacionId");

                    b.Property<double>("Potencia");

                    b.Property<long>("SistemaId");

                    b.Property<long>("TipoTecnologiaId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EnergeticInId");

                    b.HasIndex("EnergeticOutId");

                    b.HasIndex("ModoOperacionId");

                    b.HasIndex("SistemaId");

                    b.HasIndex("TipoTecnologiaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Institucion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<int>("OldId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Medidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<bool>("Compartido");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long?>("DivisionId");

                    b.Property<int>("Fases");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Numero");

                    b.Property<long>("NumeroClienteId");

                    b.Property<long>("OldId");

                    b.Property<bool>("Smart");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("NumeroClienteId");

                    b.ToTable("Medidores");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.ModoOperacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.ToTable("ModoOperaciones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.NumeroCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long?>("DivisionId");

                    b.Property<long?>("EmpresaDistribuidoraId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("NombreCliente");

                    b.Property<string>("Numero");

                    b.Property<long>("OldId");

                    b.Property<long>("TipoTarifaId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EmpresaDistribuidoraId");

                    b.HasIndex("TipoTarifaId");

                    b.ToTable("NumeroClientes");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.ParametroMedicion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<long>("UnidadesMedidaId");

                    b.HasKey("Id");

                    b.HasIndex("UnidadesMedidaId");

                    b.ToTable("ParametrosMedicion");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Provincia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<long>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("Numero");

                    b.Property<int>("Posicion");

                    b.HasKey("Id");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Rol", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("Nombre");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<int>("OldId");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Servicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Identificador");

                    b.Property<long>("InstitucionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<int>("OldId");

                    b.Property<bool>("ReportaPMG");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Sistema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.ToTable("Sistema");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.SubDivision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<long>("DivisionId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Nombre");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<long>("Version");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("SubDivisiones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoAgrupamiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoAgrupamientos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoAislacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoAislaciones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoArchivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MimeType");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoArchivos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoEdificio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<long>("OldId");

                    b.HasKey("Id");

                    b.ToTable("TipoEdificios");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoMateriales");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoPropiedad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoPropiedades");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoPuerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Factor");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoPuertas");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoSombreado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FactorSombra");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoSombreados");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoTarifa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoTarifas");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoTecho", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Factor");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoTechos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoTecnologia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoTecnologias");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoUnidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<long>("OldId");

                    b.HasKey("Id");

                    b.ToTable("TipoUnidades");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoUso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoUsos");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.TipoVentana", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FactorVentana");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoVentanas");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UnidadMedida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool?>("Active");

                    b.Property<string>("Address");

                    b.Property<string>("Apellidos");

                    b.Property<string>("Cargo");

                    b.Property<bool?>("Certificado");

                    b.Property<string>("City");

                    b.Property<long?>("ComunaId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Nacionalidad");

                    b.Property<string>("Nombres");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<int?>("OldId");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Rut");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<bool?>("Validado");

                    b.HasKey("Id");

                    b.HasIndex("ComunaId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioDivision", b =>
                {
                    b.Property<long>("DivisionId");

                    b.Property<string>("UsuarioId");

                    b.HasKey("DivisionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosDivisiones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioInstitucion", b =>
                {
                    b.Property<long>("InstitucionId");

                    b.Property<string>("UsuarioId");

                    b.HasKey("InstitucionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosInstituciones");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioRol", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.Property<string>("RolId1");

                    b.Property<string>("UsuarioId1");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RolId1");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioServicio", b =>
                {
                    b.Property<long>("ServicioId");

                    b.Property<string>("UsuarioId");

                    b.HasKey("ServicioId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosServicios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Cimiento", b =>
                {
                    b.HasBaseType("GobEfi.Web.Data.Entities.Componente");


                    b.ToTable("Cimiento");

                    b.HasDiscriminator().HasValue("Cimiento");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Piso", b =>
                {
                    b.HasBaseType("GobEfi.Web.Data.Entities.Componente");

                    b.Property<double>("Altura");

                    b.ToTable("Piso");

                    b.HasDiscriminator().HasValue("Piso");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Puerta", b =>
                {
                    b.HasBaseType("GobEfi.Web.Data.Entities.Componente");

                    b.Property<double>("Ancho");

                    b.Property<double>("Largo");

                    b.Property<long>("TipoPuertaId");

                    b.HasIndex("TipoPuertaId");

                    b.ToTable("Puerta");

                    b.HasDiscriminator().HasValue("Puerta");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Techo", b =>
                {
                    b.HasBaseType("GobEfi.Web.Data.Entities.Componente");

                    b.Property<double>("Ancho")
                        .HasColumnName("Techo_Ancho");

                    b.Property<double>("Largo")
                        .HasColumnName("Techo_Largo");

                    b.Property<long>("TipoTechoId");

                    b.HasIndex("TipoTechoId");

                    b.ToTable("Techo");

                    b.HasDiscriminator().HasValue("Techo");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Ventana", b =>
                {
                    b.HasBaseType("GobEfi.Web.Data.Entities.Componente");

                    b.Property<double>("Alto");

                    b.Property<double>("Largo")
                        .HasColumnName("Ventana_Largo");

                    b.Property<long>("TipoVentanaId");

                    b.HasIndex("TipoVentanaId");

                    b.ToTable("Ventana");

                    b.HasDiscriminator().HasValue("Ventana");
                });

            modelBuilder.Entity("GE.Data.Entities.Menu", b =>
                {
                    b.HasOne("GE.Data.Entities.MenuPanel", "MenuPanel")
                        .WithMany("Menus")
                        .HasForeignKey("MenuPanelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GE.Data.Entities.Permisos", b =>
                {
                    b.HasOne("GE.Data.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId");

                    b.HasOne("GE.Data.Entities.SubMenu", "SubMenu")
                        .WithMany("Permisos")
                        .HasForeignKey("SubMenuId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GE.Data.Entities.ReporteRol", b =>
                {
                    b.HasOne("GE.Data.Entities.Reporte", "Reporte")
                        .WithMany("ReportesRol")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Rol", "Rol")
                        .WithMany("ReportesRol")
                        .HasForeignKey("RolId");
                });

            modelBuilder.Entity("GE.Data.Entities.SubMenu", b =>
                {
                    b.HasOne("GE.Data.Entities.Menu", "Menu")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.ArchivoAdjunto", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division", "Division")
                        .WithMany("Adjuntos")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoArchivo", "TipoArchivo")
                        .WithMany()
                        .HasForeignKey("TipoArchivoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Componente", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division", "Division")
                        .WithMany("Componentes")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoAislacion", "TipoAislacion")
                        .WithMany()
                        .HasForeignKey("TipoAislacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoMaterial", "TipoMaterial")
                        .WithMany()
                        .HasForeignKey("TipoMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Compra", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division", "Division")
                        .WithMany("Compras")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Energetico", "Energetico")
                        .WithMany("Compras")
                        .HasForeignKey("EnergeticoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.ArchivoAdjunto", "Factura")
                        .WithOne("Compra")
                        .HasForeignKey("GobEfi.Web.Data.Entities.Compra", "FacturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GobEfi.Web.Data.Entities.NumeroCliente", "NumeroCliente")
                        .WithMany("Compras")
                        .HasForeignKey("NumeroClienteId");

                    b.HasOne("GobEfi.Web.Data.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.CompraMedidor", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Compra", "Compra")
                        .WithMany("CompraMedidor")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Medidor", "Medidor")
                        .WithMany("CompraMedidor")
                        .HasForeignKey("MedidorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GobEfi.Web.Data.Entities.ParametroMedicion", "ParametroMedicion")
                        .WithMany()
                        .HasForeignKey("ParametroMedicionId");

                    b.HasOne("GobEfi.Web.Data.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Comuna", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Provincia", "Provincia")
                        .WithMany("Comunas")
                        .HasForeignKey("ProvinciaId");

                    b.HasOne("GobEfi.Web.Data.Entities.Region", "Region")
                        .WithMany("Comunas")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Division", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Edificio", "Edificio")
                        .WithMany()
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoAgrupamiento", "TipoAgrupamiento")
                        .WithMany()
                        .HasForeignKey("TipoAgrupamientoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoPropiedad", "TipoPropiedad")
                        .WithMany()
                        .HasForeignKey("TipoPropiedadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoUnidad", "TipoUnidad")
                        .WithMany()
                        .HasForeignKey("TipoUnidadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoUso", "TipoUso")
                        .WithMany()
                        .HasForeignKey("TipoUsoId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Edificio", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Comuna", "Comuna")
                        .WithMany()
                        .HasForeignKey("ComunaId");

                    b.HasOne("GobEfi.Web.Data.Entities.TipoEdificio", "TipoEdificio")
                        .WithMany()
                        .HasForeignKey("TipoEdificioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EmpresaDistribuidora", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Energetico", "Energetico")
                        .WithMany()
                        .HasForeignKey("EnergeticoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EmpresaDistribuidoraComuna", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Comuna", "Comuna")
                        .WithMany()
                        .HasForeignKey("ComunaId");

                    b.HasOne("GobEfi.Web.Data.Entities.EmpresaDistribuidora", "EmpresaDistribuidora")
                        .WithMany()
                        .HasForeignKey("EmpresaDistribuidoraId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EnergeticoDivision", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division", "Division")
                        .WithMany("Energeticos")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Energetico", "Energetico")
                        .WithMany("Divisiones")
                        .HasForeignKey("EnergeticoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.NumeroCliente", "NumeroCliente")
                        .WithMany()
                        .HasForeignKey("NumeroClienteId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.EnergeticoUnidadMedida", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Energetico", "Energetico")
                        .WithMany("EnergeticoUnMedida")
                        .HasForeignKey("EnergeticoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany("EnergeticoUnidadMedidas")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Equipo", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division")
                        .WithMany("Equipos")
                        .HasForeignKey("DivisionId");

                    b.HasOne("GobEfi.Web.Data.Entities.Energetico", "EnergeticIn")
                        .WithMany()
                        .HasForeignKey("EnergeticInId");

                    b.HasOne("GobEfi.Web.Data.Entities.Energetico", "EnergeticOut")
                        .WithMany()
                        .HasForeignKey("EnergeticOutId");

                    b.HasOne("GobEfi.Web.Data.Entities.ModoOperacion", "ModoOperacion")
                        .WithMany()
                        .HasForeignKey("ModoOperacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.TipoTecnologia", "TipoTecnologia")
                        .WithMany()
                        .HasForeignKey("TipoTecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Medidor", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division")
                        .WithMany("Medidores")
                        .HasForeignKey("DivisionId");

                    b.HasOne("GobEfi.Web.Data.Entities.NumeroCliente", "NumeroCliente")
                        .WithMany("Medidores")
                        .HasForeignKey("NumeroClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.NumeroCliente", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division")
                        .WithMany("NumerosClientes")
                        .HasForeignKey("DivisionId");

                    b.HasOne("GobEfi.Web.Data.Entities.EmpresaDistribuidora", "EmpresaDistribuidora")
                        .WithMany()
                        .HasForeignKey("EmpresaDistribuidoraId");

                    b.HasOne("GobEfi.Web.Data.Entities.TipoTarifa", "TipoTarifa")
                        .WithMany()
                        .HasForeignKey("TipoTarifaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.ParametroMedicion", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.UnidadMedida", "UnidadesMedida")
                        .WithMany("ParametrosMedicion")
                        .HasForeignKey("UnidadesMedidaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Provincia", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Region", "Region")
                        .WithMany("Provincias")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Servicio", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Institucion", "Institucion")
                        .WithMany("Servicios")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.SubDivision", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division", "Division")
                        .WithMany("SubDivisiones")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Usuario", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Comuna", "Comuna")
                        .WithMany()
                        .HasForeignKey("ComunaId");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioDivision", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Division", "Division")
                        .WithMany("UsuariosDivisiones")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosDivisiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioInstitucion", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Institucion", "Institucion")
                        .WithMany("UsuariosInstituciones")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosInstituciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioRol", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId1");

                    b.HasOne("GobEfi.Web.Data.Entities.Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.UsuarioServicio", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Servicio", "Servicio")
                        .WithMany("UsuariosServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GobEfi.Web.Data.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosServicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Rol")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Usuario")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Usuario")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Puerta", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.TipoPuerta", "TipoPuerta")
                        .WithMany()
                        .HasForeignKey("TipoPuertaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Techo", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.TipoTecho", "TipoTecho")
                        .WithMany()
                        .HasForeignKey("TipoTechoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GobEfi.Web.Data.Entities.Ventana", b =>
                {
                    b.HasOne("GobEfi.Web.Data.Entities.TipoVentana", "TipoVentana")
                        .WithMany()
                        .HasForeignKey("TipoVentanaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
