-- =============================================
-- Author:		Ivan Molina H (APIUX)
-- Create date: 08/07/2020
-- Description:	Funcion tipo tabla que devuelve simplemente Servicios
--              con sus Ids's, Nombres y Anexos (si es que tiene Anexo)
--              Se usa en Aplicacion Orquestadora
-- =============================================
CREATE FUNCTION FNT_SERVICIOS_ORQUESTADOR()
RETURNS @T TABLE(
Int64PK bigint primary key, --Corresponde al id servicio
NombreServicio varchar(512),
AnexoId int
)
AS
BEGIN
	declare @anexo_servicio table
	(ServicioId bigint PRIMARY KEY, 
	 AnexoId bigint UNIQUE NOT NULL)


	insert @anexo_servicio (ServicioId, AnexoId) values(556, 	1)
	insert @anexo_servicio (ServicioId, AnexoId) values(558, 	2)
	insert @anexo_servicio (ServicioId, AnexoId) values(721, 	3)
	insert @anexo_servicio (ServicioId, AnexoId) values(654, 	4)
	insert @anexo_servicio (ServicioId, AnexoId) values(460, 	5)
	insert @anexo_servicio (ServicioId, AnexoId) values(448, 	6)
	insert @anexo_servicio (ServicioId, AnexoId) values(459, 	7)
	insert @anexo_servicio (ServicioId, AnexoId) values(640, 	8)
	insert @anexo_servicio (ServicioId, AnexoId) values(548, 	9)
	insert @anexo_servicio (ServicioId, AnexoId) values(537, 	10)
	insert @anexo_servicio (ServicioId, AnexoId) values(719, 	11)
	insert @anexo_servicio (ServicioId, AnexoId) values(564, 	12)
	insert @anexo_servicio (ServicioId, AnexoId) values(454, 	13)
	insert @anexo_servicio (ServicioId, AnexoId) values(529, 	14)
	insert @anexo_servicio (ServicioId, AnexoId) values(700, 	15)
	insert @anexo_servicio (ServicioId, AnexoId) values(639, 	16)
	insert @anexo_servicio (ServicioId, AnexoId) values(571, 	17)
	insert @anexo_servicio (ServicioId, AnexoId) values(628, 	18)
	insert @anexo_servicio (ServicioId, AnexoId) values(624, 	19)
	insert @anexo_servicio (ServicioId, AnexoId) values(547, 	20)
	insert @anexo_servicio (ServicioId, AnexoId) values(1507, 	21)
	insert @anexo_servicio (ServicioId, AnexoId) values(469, 	22)
	insert @anexo_servicio (ServicioId, AnexoId) values(625, 	23)
	insert @anexo_servicio (ServicioId, AnexoId) values(627, 	24)
	insert @anexo_servicio (ServicioId, AnexoId) values(720, 	25)
	insert @anexo_servicio (ServicioId, AnexoId) values(626, 	26)
	insert @anexo_servicio (ServicioId, AnexoId) values(642, 	27)
	insert @anexo_servicio (ServicioId, AnexoId) values(604, 	28)
	insert @anexo_servicio (ServicioId, AnexoId) values(632, 	29)
	insert @anexo_servicio (ServicioId, AnexoId) values(1124, 	30)
	insert @anexo_servicio (ServicioId, AnexoId) values(1505, 	31)
	insert @anexo_servicio (ServicioId, AnexoId) values(644, 	32)
	insert @anexo_servicio (ServicioId, AnexoId) values(550, 	33)
	insert @anexo_servicio (ServicioId, AnexoId) values(533, 	34)
	insert @anexo_servicio (ServicioId, AnexoId) values(697, 	35)
	insert @anexo_servicio (ServicioId, AnexoId) values(652, 	36)
	insert @anexo_servicio (ServicioId, AnexoId) values(569, 	37)
	insert @anexo_servicio (ServicioId, AnexoId) values(503, 	38)
	insert @anexo_servicio (ServicioId, AnexoId) values(504, 	39)
	insert @anexo_servicio (ServicioId, AnexoId) values(512, 	40)
	insert @anexo_servicio (ServicioId, AnexoId) values(505, 	41)
	insert @anexo_servicio (ServicioId, AnexoId) values(1121, 	42)
	insert @anexo_servicio (ServicioId, AnexoId) values(507, 	43)
	insert @anexo_servicio (ServicioId, AnexoId) values(511, 	44)
	insert @anexo_servicio (ServicioId, AnexoId) values(515, 	45)
	insert @anexo_servicio (ServicioId, AnexoId) values(513, 	46)
	insert @anexo_servicio (ServicioId, AnexoId) values(508, 	47)
	insert @anexo_servicio (ServicioId, AnexoId) values(514, 	48)
	insert @anexo_servicio (ServicioId, AnexoId) values(502, 	49)
	insert @anexo_servicio (ServicioId, AnexoId) values(506, 	50)
	insert @anexo_servicio (ServicioId, AnexoId) values(470, 	51)
	insert @anexo_servicio (ServicioId, AnexoId) values(637, 	52)
	insert @anexo_servicio (ServicioId, AnexoId) values(648, 	53)
	insert @anexo_servicio (ServicioId, AnexoId) values(653, 	54)
	insert @anexo_servicio (ServicioId, AnexoId) values(649, 	55)
	insert @anexo_servicio (ServicioId, AnexoId) values(466, 	56)
	insert @anexo_servicio (ServicioId, AnexoId) values(710, 	57)
	insert @anexo_servicio (ServicioId, AnexoId) values(633, 	58)
	insert @anexo_servicio (ServicioId, AnexoId) values(699, 	59)
	insert @anexo_servicio (ServicioId, AnexoId) values(538, 	60)
	insert @anexo_servicio (ServicioId, AnexoId) values(452, 	61)
	insert @anexo_servicio (ServicioId, AnexoId) values(559, 	62)
	insert @anexo_servicio (ServicioId, AnexoId) values(376, 	63)
	insert @anexo_servicio (ServicioId, AnexoId) values(636, 	64)
	insert @anexo_servicio (ServicioId, AnexoId) values(493, 	65)
	insert @anexo_servicio (ServicioId, AnexoId) values(680, 	66)
	insert @anexo_servicio (ServicioId, AnexoId) values(437, 	67)
	insert @anexo_servicio (ServicioId, AnexoId) values(453, 	68)
	insert @anexo_servicio (ServicioId, AnexoId) values(456, 	69)
	insert @anexo_servicio (ServicioId, AnexoId) values(450, 	70)
	insert @anexo_servicio (ServicioId, AnexoId) values(566, 	71)
	insert @anexo_servicio (ServicioId, AnexoId) values(447, 	72)
	insert @anexo_servicio (ServicioId, AnexoId) values(638, 	73)
	insert @anexo_servicio (ServicioId, AnexoId) values(535, 	74)
	insert @anexo_servicio (ServicioId, AnexoId) values(463, 	75)
	insert @anexo_servicio (ServicioId, AnexoId) values(491, 	76)
	insert @anexo_servicio (ServicioId, AnexoId) values(567, 	77)
	insert @anexo_servicio (ServicioId, AnexoId) values(546, 	78)
	insert @anexo_servicio (ServicioId, AnexoId) values(568, 	79)
	insert @anexo_servicio (ServicioId, AnexoId) values(545, 	80)
	insert @anexo_servicio (ServicioId, AnexoId) values(645, 	81)
	insert @anexo_servicio (ServicioId, AnexoId) values(449, 	82)
	insert @anexo_servicio (ServicioId, AnexoId) values(701, 	83)
	insert @anexo_servicio (ServicioId, AnexoId) values(716, 	84)
	insert @anexo_servicio (ServicioId, AnexoId) values(709, 	85)
	insert @anexo_servicio (ServicioId, AnexoId) values(528, 	86)
	insert @anexo_servicio (ServicioId, AnexoId) values(534, 	87)
	insert @anexo_servicio (ServicioId, AnexoId) values(702, 	88)
	insert @anexo_servicio (ServicioId, AnexoId) values(526, 	89)
	insert @anexo_servicio (ServicioId, AnexoId) values(557, 	90)
	insert @anexo_servicio (ServicioId, AnexoId) values(500, 	91)
	insert @anexo_servicio (ServicioId, AnexoId) values(682, 	92)
	insert @anexo_servicio (ServicioId, AnexoId) values(695, 	93)
	insert @anexo_servicio (ServicioId, AnexoId) values(683, 	94)
	insert @anexo_servicio (ServicioId, AnexoId) values(691, 	95)
	insert @anexo_servicio (ServicioId, AnexoId) values(684, 	96)
	insert @anexo_servicio (ServicioId, AnexoId) values(689, 	97)
	insert @anexo_servicio (ServicioId, AnexoId) values(694, 	98)
	insert @anexo_servicio (ServicioId, AnexoId) values(692, 	99)
	insert @anexo_servicio (ServicioId, AnexoId) values(687, 	100)
	insert @anexo_servicio (ServicioId, AnexoId) values(1122, 	101)
	insert @anexo_servicio (ServicioId, AnexoId) values(681, 	102)
	insert @anexo_servicio (ServicioId, AnexoId) values(685, 	103)
	insert @anexo_servicio (ServicioId, AnexoId) values(688, 	104)
	insert @anexo_servicio (ServicioId, AnexoId) values(686, 	105)
	insert @anexo_servicio (ServicioId, AnexoId) values(690, 	106)
	insert @anexo_servicio (ServicioId, AnexoId) values(693, 	107)
	insert @anexo_servicio (ServicioId, AnexoId) values(635, 	108)
	insert @anexo_servicio (ServicioId, AnexoId) values(446, 	109)
	insert @anexo_servicio (ServicioId, AnexoId) values(1095, 	110)
	insert @anexo_servicio (ServicioId, AnexoId) values(494, 	111)
	insert @anexo_servicio (ServicioId, AnexoId) values(525, 	112)
	insert @anexo_servicio (ServicioId, AnexoId) values(554, 	113)
	insert @anexo_servicio (ServicioId, AnexoId) values(718, 	114)
	insert @anexo_servicio (ServicioId, AnexoId) values(458, 	115)
	insert @anexo_servicio (ServicioId, AnexoId) values(703, 	116)
	insert @anexo_servicio (ServicioId, AnexoId) values(711, 	117)
	insert @anexo_servicio (ServicioId, AnexoId) values(1123, 	118)
	insert @anexo_servicio (ServicioId, AnexoId) values(722, 	119)
	insert @anexo_servicio (ServicioId, AnexoId) values(527, 	120)
	insert @anexo_servicio (ServicioId, AnexoId) values(496, 	121)
	insert @anexo_servicio (ServicioId, AnexoId) values(643, 	122)
	insert @anexo_servicio (ServicioId, AnexoId) values(656, 	123)
	insert @anexo_servicio (ServicioId, AnexoId) values(655, 	124)
	insert @anexo_servicio (ServicioId, AnexoId) values(696, 	125)
	insert @anexo_servicio (ServicioId, AnexoId) values(451, 	126)
	insert @anexo_servicio (ServicioId, AnexoId) values(679, 	127)
	insert @anexo_servicio (ServicioId, AnexoId) values(465, 	128)
	insert @anexo_servicio (ServicioId, AnexoId) values(501, 	129)
	insert @anexo_servicio (ServicioId, AnexoId) values(462, 	130)
	insert @anexo_servicio (ServicioId, AnexoId) values(641, 	131)
	insert @anexo_servicio (ServicioId, AnexoId) values(552, 	132)
	insert @anexo_servicio (ServicioId, AnexoId) values(1510, 	133)
	insert @anexo_servicio (ServicioId, AnexoId) values(461, 	134)
	insert @anexo_servicio (ServicioId, AnexoId) values(540, 	135)
	insert @anexo_servicio (ServicioId, AnexoId) values(647, 	136)
	insert @anexo_servicio (ServicioId, AnexoId) values(657, 	137)
	insert @anexo_servicio (ServicioId, AnexoId) values(646, 	138)
	insert @anexo_servicio (ServicioId, AnexoId) values(634, 	139)
	insert @anexo_servicio (ServicioId, AnexoId) values(464, 	140)
	insert @anexo_servicio (ServicioId, AnexoId) values(555, 	141)
	insert @anexo_servicio (ServicioId, AnexoId) values(551, 	142)

	insert into @T(Int64PK, AnexoId, NombreServicio)
	SELECT s.Id, ISNULL(a.AnexoId,-1) , s.Nombre from Servicios s
	left join @anexo_servicio a on a.ServicioId = s.Id
	where s.Active = 1
	RETURN
END
GO
