// <auto-generated />
using GobEfi.FV.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GobEfi.FV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210106174754_modelos_table")]
    partial class modelos_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GobEfi.FV.API.Models.Entities.ModeloEm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Acumulacion_energia_bateria")
                        .HasColumnType("int");

                    b.Property<string>("Autonomia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacidad_convertidor_vehiculo_electrico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carroceria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria_vehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cilindrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Co2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo_informe_tecnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Combustible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Eliminar")
                        .HasColumnType("int");

                    b.Property<string>("Empresa_homologacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_homologacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdEm")
                        .HasColumnType("bigint");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Norma_emisiones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propulsion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento_carretera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento_ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento_enchufable_combustible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento_enchufable_electrico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento_mixto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rendimiento_puro_electrico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_de_conector_ac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_de_conector_dc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("GobEfi.FV.API.Models.Entities.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<long>("CilindradaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kmxlt")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MarcaId")
                        .HasColumnType("bigint");

                    b.Property<long>("MinisterioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ModeloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PropulsionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TipoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoPropiedadId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
